// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVXTWtxQ_y-9GgqqDngCo9RttypbOnNA4',
    appId: '1:749493468449:web:21e33e859aae67cec1d260',
    messagingSenderId: '749493468449',
    projectId: 'ai-nutrition-identifier',
    authDomain: 'ai-nutrition-identifier.firebaseapp.com',
    storageBucket: 'ai-nutrition-identifier.firebasestorage.app',
    measurementId: 'G-2C0K0T0HMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHJhsiWDav4b1QPHy9zC9oP2x6p8qwPg4',
    appId: '1:749493468449:android:e46dd595d0a15175c1d260',
    messagingSenderId: '749493468449',
    projectId: 'ai-nutrition-identifier',
    storageBucket: 'ai-nutrition-identifier.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-VFha_2sjF30W0eqoEGyEMT0atNdEe5o',
    appId: '1:749493468449:ios:3890e40e64c2fbb6c1d260',
    messagingSenderId: '749493468449',
    projectId: 'ai-nutrition-identifier',
    storageBucket: 'ai-nutrition-identifier.firebasestorage.app',
    iosBundleId: 'com.example.aiNutritionIdentifier',
  );

}